# -*- coding: utf-8 -*-
"""linear_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hY0wP_xh4L0RP-RF7X8NEBAp0JJftW8q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


'''hypothesis:
  h(x) = theta(0) + theta(1).x

vector:
  h(x) = theta[T].X'''

'''Cost function:
  J(theta) = 1/2 * sum(hypothesis - output)²'''

'''Gradient decsent:
  theta = theta - alpha * gradient

  gradient = sum(hypotesis - output) * X
  '''

"""Simple regression

Predict function
"""

def predict(X, theta):
  return X.dot(theta) # hypothesis function

"""Cost Function"""

def cost(X, Y, theta):
  return np.sum((predict(X, theta) - y) ** 2) / 2 * len(Y)

"""Gradient functions"""

# define gradient
def gradient(X, y, theta):
  n = len(y)
  return (X.T.dot(predict(X, theta) - y)) / n

def gradient_descent(theta, X, y, lr, epochs):

  for i in range(epochs):
      # if i % 500 == 0:
      #   print(cost(X, y, theta))
      theta = theta - lr * gradient(X, y, theta)
      # defining learning rate to be 0.1 and convergence iteration to be 1000

  return theta

"""Normal **Equation**"""

def j_cost(X, y):
  return X.T.dot(y)

def normal_eq(X, y):
  return np.linalg.inv((X.T.dot(X))).dot(j_cost(X, y))

"""Test runs (training)"""

X = np.array([[1, 1],
             [1, 2],
             [1, 3]])

y = np.array([2, 4, 6])

theta = np.array([0, 0]) # initialze theta

theta_final = gradient_descent(theta, X, y, 0.01, 5000) # getting the theta after gradient iteration
theta_2 = normal_eq(X, y) # getting theta matrix with normal equation

print(theta_final)
print(theta_2)

"""Testing with the new theta

"""

y_pred = predict(X, theta_final)
y_pred2 = predict(X, theta_2)

print(y_pred)
print(y_pred2)
print(cost(X, y, theta_final))
print(cost(X, y, theta_2))
# np.allclose(X.dot(theta_final), y, atol=1e-2)
np.allclose(X.dot(theta_2), y, atol=1e-2)

"""Testing

Multiple variable
"""

'''We will use the normal equation and increase the dimension of both our matrices

let's go for the equation: y = 2x(1) + 3x(2) - 5x(3)'''

X = np.array([
    [1, 1000, 2, 10],
    [1, 1200, 3, 8],
    [1, 1500, 3, 5],
    [1, 1800, 4, 3],
    [1, 2000, 4, 2],
    [1, 2200, 5, 1]
])

# Target: Price
y = np.array([60, 84, 105, 128, 142, 165])

theta_new = np.array([0, 0, 0, 0])

theta_3 = normal_eq(X, y)

print(theta_3)

pred1 = predict(X, theta_3)

print(pred1)
np.allclose(X.dot(theta_3), y, atol=1e-2)

plt.scatter(X[:, 1], y)
plt.plot(X[:, 1], pred1, color='red')
plt.show()

X2 = np.array([[1, 4],
               [1, 5]])

predict(X2, theta_2)

"""Working with dataset"""

df = pd.read_csv('test.csv')
print(df.info())

from sklearn.model_selection import train_test_split

X = df['x'].values
y = df['y'].values

# Split the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

X_train = np.c_[np.ones(X_train.shape[0]), X_train]
X_test = np.c_[np.ones(X_test.shape[0]), X_test]

theta = np.array([0.0, 0.0])

print(np.max(X))
print(np.max(y))

theta_final = gradient_descent(theta, X_train, y_train, 0.0005, 5000)
print(gradient(X_train, y_train, theta))
print(theta_final)

y_predict = predict(X_test, theta_final)
print(y_predict)

plt.scatter(X_train[:, 1], y_train)
plt.plot(X_test[:, 1], y_predict, color='red')
plt.show()